---
- name: Set swappiness to 0 so server will only swap if running out of memory. A monitoring check should verify that 0 bytes of swap are used.
  sysctl: name=vm.swappiness
          value=0
          state=present
  sudo: {{ sudo }}
